"""crear tablas clientes y proyectos, enlazar cotizacion

Revision ID: 036e02095cb0
Revises: f08f77f098c9
Create Date: 2026-09-22 10:53:54.007139
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '036e02095cb0'
down_revision: str | None = 'f08f77f098c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_identificacion', sa.Enum('cedula', 'ruc', 'pasaporte', name='tipo_identificacion'), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_identificacion'), 'clientes', ['identificacion'], unique=True)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'en_diseno', 'disenado', 'cotizado', name='estado_proyecto'), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_cliente_id'), 'proyectos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=False)
    op.add_column('cotizaciones', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('cotizaciones', sa.Column('proyecto_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cotizaciones_cliente_id'), 'cotizaciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_proyecto_id'), 'cotizaciones', ['proyecto_id'], unique=False)
    # Nombres explícitos: el autogenerado los dejó en None, y entonces el
    # downgrade no sabe qué constraint eliminar.
    op.create_foreign_key(
        'fk_cotizaciones_cliente_id_clientes',
        'cotizaciones', 'clientes',
        ['cliente_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_cotizaciones_proyecto_id_proyectos',
        'cotizaciones', 'proyectos',
        ['proyecto_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cotizaciones_proyecto_id_proyectos', 'cotizaciones', type_='foreignkey')
    op.drop_constraint('fk_cotizaciones_cliente_id_clientes', 'cotizaciones', type_='foreignkey')
    op.drop_index(op.f('ix_cotizaciones_proyecto_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_cliente_id'), table_name='cotizaciones')
    op.drop_column('cotizaciones', 'proyecto_id')
    op.drop_column('cotizaciones', 'cliente_id')
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_cliente_id'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_identificacion'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###

    # Postgres conserva los tipos ENUM aunque se elimine la tabla que los
    # usa. Sin esto, un `upgrade` posterior falla con DuplicateObject.
    # Van al final, cuando las tablas que los referencian ya no existen.
    sa.Enum(name='estado_proyecto').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='tipo_identificacion').drop(op.get_bind(), checkfirst=False)
