"""agregar desglose y materiales cotizados a cotizaciones

Revision ID: 682c93cc4b63
Revises: b7d2e5f18c40
Create Date: 2026-10-02 21:22:07.021573
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '682c93cc4b63'
down_revision: str | None = 'b7d2e5f18c40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales_cotizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_cotizados_cotizacion_id'), 'materiales_cotizados', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_materiales_cotizados_material_id'), 'materiales_cotizados', ['material_id'], unique=False)
    op.add_column('cotizaciones', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cotizaciones', sa.Column('addendum_monto', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cotizaciones', sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cotizaciones', sa.Column('iva_monto', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cotizaciones', sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'total')
    op.drop_column('cotizaciones', 'iva_monto')
    op.drop_column('cotizaciones', 'iva_porcentaje')
    op.drop_column('cotizaciones', 'addendum_monto')
    op.drop_column('cotizaciones', 'subtotal')
    op.drop_index(op.f('ix_materiales_cotizados_material_id'), table_name='materiales_cotizados')
    op.drop_index(op.f('ix_materiales_cotizados_cotizacion_id'), table_name='materiales_cotizados')
    op.drop_table('materiales_cotizados')
    # ### end Alembic commands ###
