"""crear tablas cotizaciones e items_cotizacion

Revision ID: 35771a9c2ed6
Revises: 5d904e910ae8
Create Date: 2026-09-22 04:26:50.306632
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35771a9c2ed6'
down_revision: str | None = '5d904e910ae8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_proforma', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=False),
    sa.Column('cliente_empresa', sa.String(length=150), nullable=True),
    sa.Column('cliente_email', sa.String(length=255), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('proyecto_nombre', sa.String(length=150), nullable=True),
    sa.Column('addendum_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('cotizada', 'despachada', 'recibida', 'instalada', name='estado_cotizacion'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_numero_proforma'), 'cotizaciones', ['numero_proforma'], unique=True)
    op.create_table('items_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('paneles_largo', sa.Integer(), nullable=False),
    sa.Column('paneles_ancho', sa.Integer(), nullable=False),
    sa.Column('bloques', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_cotizacion')
    op.drop_index(op.f('ix_cotizaciones_numero_proforma'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###

    # El ENUM de Postgres es un tipo aparte de la columna que lo usa:
    # drop_table no lo elimina, hay que hacerlo a mano o queda huérfano.
    sa.Enum(name='estado_cotizacion').drop(op.get_bind(), checkfirst=False)
