"""crear tablas materiales y precios_material

Revision ID: f08f77f098c9
Revises: 35771a9c2ed6
Create Date: 2026-09-22 04:36:28.365406
"""

from collections.abc import Sequence
from datetime import datetime, timezone
from decimal import Decimal

from alembic import op
import sqlalchemy as sa


revision: str = 'f08f77f098c9'
down_revision: str | None = '35771a9c2ed6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Catálogo fijo del cálculo f(L,A,B) (RF-06) y sus precios vigentes desde
# enero 2026. `nombre` es un placeholder legible por código: el nombre
# comercial definitivo se ajusta después desde la administración de
# precios (RF-09) sin tocar el `codigo`, que es lo que usa el cálculo.
#
# LOG (logística) en $0.00 es a propósito, no un olvido: así lo dieron los
# precios vigentes de HEXtructure. Queda para que el Gerente General lo
# configure desde RF-09 cuando corresponda.
MATERIALES_INICIALES = [
    ("VAR1650", "Varilla 1650mm", Decimal("7.20")),
    ("VAR1350", "Varilla 1350mm", Decimal("6.20")),
    ("HEX_V18MM", "Hexagonal V 18mm", Decimal("2.40")),
    ("SOP_A", "Soporte A", Decimal("4.75")),
    ("SOP_V", "Soporte V", Decimal("4.75")),
    ("SOP_V_E", "Soporte V extremo", Decimal("3.25")),
    ("ANT_B", "Antena base", Decimal("2.10")),
    ("ANT_VAR", "Antena varilla", Decimal("3.20")),
    ("CLAMP_F", "Clamp final", Decimal("1.00")),
    ("CLAMP_I", "Clamp intermedio", Decimal("1.00")),
    ("LOG", "Logística", Decimal("0.00")),
]

VIGENTE_DESDE_INICIAL = datetime(2026, 1, 1, tzinfo=timezone.utc)


def upgrade() -> None:
    """Aplica los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_codigo'), 'materiales', ['codigo'], unique=True)
    op.create_table('precios_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Postgres no indexa las FK solas; sin esto, "el historial de precios
    # de este material" escanea toda la tabla. Con 11 materiales no se
    # nota, pero es la consulta más frecuente del módulo.
    op.create_index(
        op.f('ix_precios_material_material_id'),
        'precios_material',
        ['material_id'],
        unique=False,
    )
    # Garantiza un solo precio vigente (vigente_hasta IS NULL) por material
    # a nivel de base: si un bug de RF-09 llega a insertar dos, el cálculo
    # no sabría cuál usar.
    op.create_index(
        'ux_precio_vigente_por_material',
        'precios_material',
        ['material_id'],
        unique=True,
        postgresql_where=sa.text('vigente_hasta IS NULL'),
    )
    # ### end Alembic commands ###

    # ─── Datos: catálogo de materiales + precio vigente desde ene/2026 ───
    materiales_tabla = sa.table(
        'materiales',
        sa.column('id', sa.Integer),
        sa.column('codigo', sa.String),
        sa.column('nombre', sa.String),
        sa.column('unidad', sa.String),
        sa.column('activo', sa.Boolean),
    )
    precios_tabla = sa.table(
        'precios_material',
        sa.column('material_id', sa.Integer),
        sa.column('precio', sa.Numeric),
        sa.column('vigente_desde', sa.DateTime),
        sa.column('vigente_hasta', sa.DateTime),
    )

    bind = op.get_bind()
    for material_id, (codigo, nombre, precio) in enumerate(MATERIALES_INICIALES, start=1):
        bind.execute(
            materiales_tabla.insert().values(
                id=material_id,
                codigo=codigo,
                nombre=nombre,
                unidad="unidad",
                activo=True,
            )
        )
        bind.execute(
            precios_tabla.insert().values(
                material_id=material_id,
                precio=precio,
                vigente_desde=VIGENTE_DESDE_INICIAL,
                vigente_hasta=None,
            )
        )

    # El id de materiales se asignó a mano arriba para poder enlazarlo con
    # su precio en el mismo paso; hay que realinear la secuencia de
    # Postgres o el próximo INSERT sin id explícito choca con estos.
    op.execute(
        "SELECT setval('materiales_id_seq', (SELECT MAX(id) FROM materiales))"
    )


def downgrade() -> None:
    """Revierte los cambios."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_precio_vigente_por_material', table_name='precios_material')
    op.drop_index(op.f('ix_precios_material_material_id'), table_name='precios_material')
    op.drop_table('precios_material')
    op.drop_index(op.f('ix_materiales_codigo'), table_name='materiales')
    op.drop_table('materiales')
    # ### end Alembic commands ###
